version: "3"
services:
  pong-ui:
    container_name: pong-ui
    restart: unless-stopped
    build:
      context: pong-ui/
    image: pong-ui
    depends_on:
      - pong-server
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - ./pong-ui/src:/app/src
  pong-server:
    container_name: pong-server
    restart: unless-stopped
    build:
      context: pong-server/
    image: pong-server
    env_file:
      - .env
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    volumes:
      - ./pong-server/src:/app/src
